### ISSUE TITLE
WriteState type conversion can panic

### ISSUE THREAD

**Issue by natefinch** [volatiletech/authboss-clientstate#1]
https://github.com/volatiletech/authboss-clientstate/blob/master/sessions.go#L72

You should basically never do a type conversion without the `, ok` pattern.  This method even already returns an error, so it would be trivial to just return an error that the type is unexpected.

I hit this in trying to get around https://github.com/volatiletech/authboss/issues/181 by just allowing the state to be set to nil... but then it panics here.  Clearly the state shouldn't be nil... but there's also no reason not to do the checked type conversion.

**Comment by aarondl** [comment]
It's actually intentional that it panics, because it indicates that something has gone horribly, horribly wrong. That type conversion should never fail because the thing that put the state there to begin with should have been that exact same file just a few lines above, so if it's not getting the exact same type (and something non-nil) that it put in back then there's been some breakage in the API of Authboss or something else equally as devastating.

A panic in this instance saves you from believing that your app can recover from such a situation, which it cannot. And should not. It should crash and burn as this is completely inoperable. An error is handle-able, the situation you encountered is not because it won't fix itself if you log the error and try again later, your app is permanently broken.

So I respectfully disagree with your assessment of the issue here as well as the phrase that you should never do type assertions without the `, ok` pattern, there's a place for every tool, including panic. In this instance it's just because we can't verify these types of things at compile time we're forced to do so at runtime, this is just my way of ensuring that it "doesn't compile".

Hopefully that seems reasonable.

**Comment by natefinch** [comment]
Sorry to state it as "you should never"... that's not a great way to start an issue :)

I guess my argument would be that the default panic is not worded well, and it could be worded more clearly for this specific problem.  Also, this is an exported method on an exported type, so there's not really a guarantee that someone's passing in the right data (I know that this is only intended to be used by authboss, but still).

**Comment by aarondl** [comment]
I don't disagree with anything you've said. But the circumstance and the likelihood of running into this error is such that I remain unconvinced anything needs to change. Always good to have the conversation though.
